### ISSUE TITLE
This sample no longer works

### ISSUE THREAD

**Issue by drmanhatin** [Azure-Samples/cognitive-services-onnx-customvision-sample#11]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ X ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Clone the repo, export and insert one of your own CustomVision models. Error on LoadFromStreamAsync:
`Node (slice) has input size 3 not in range [min=1, max=1].`

### Any log messages given by the failure
>

`Node (slice) has input size 3 not in range [min=1, max=1].`

### Expected/desired behavior
>

Model should load

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Various windows10 versions

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by shonohs** [comment]
Thanks for reporting! It sounds like the onnx runtime version of this project is too old. We'll look into it.

**Comment by shonohs** [comment]
I couldn't reproduce the issue. The error message suggests that the model has a Slice op, but our classification models don't have it. 

Please make sure our classification model is used. Object Detection models are not supported by this sample app.
