### ISSUE TITLE
Models trained using General [S1] compact domain don't work in the application

### ISSUE THREAD

**Issue by pmk-gh** [Azure-Samples/cognitive-services-onnx-customvision-sample#12]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Train a custom image classification model on Azure Custom Vision as described on README ("You must choose a "compact" domain such as General (compact) to be able to export your classifier.") , but use **General [S1] compact** domain. Export the model to ONNX format and add the model to Assets folder of the project and update the initialization of the constant "_ourOnnxFileName" to the name of the new model.

### Any log messages given by the failure
> During model loading, the application displays "Failed to load model with error: Unknown model file format version"

### Expected/desired behavior
> According to README, the application should work generally with models trained with compact domain, while in reality it can't work with models trained using [S1] compact domain. That should be emphasized in the README that **General (compact)** domain is required rather than _any_ compact domain.

### OS and Version?
> Windows 10

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by shonohs** [comment]
Sorry for the delayed response. This repository is no longer actively maintained. We will disable this repository soon.
