### ISSUE TITLE
Update sample README

### ISSUE THREAD

**Issue by fierval** [Azure-Samples/cognitive-services-onnx-customvision-sample#5]
### Mention any other details that might be useful

In the README file under **Adding your own sample model of your own classifier**:
2. Export your model - should probably refer to ONNX, not Tensorflow
6. Add to list variable... There is no list variable anymore, just the one called `_ourOnnxFileName`.
8. No combobox for model selection
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by shonohs** [comment]
Thanks, and sorry for late response. We have fixed those issues.
