### ISSUE TITLE
ReadMe Needs updating

### ISSUE THREAD

**Issue by oscarjaergren** [Azure-Samples/cognitive-services-onnx-customvision-sample#9]
This project no longer works to run by following the Read Me instructions, as Number 6 in particular no longer applies

6. "In the MainPage.xaml.cs file set the "_ourOnnxFileName" constant to the name of model just added and set the "_numLabels" constant to the number of labels that the model contains."

There is no _numlabels

**Comment by shonohs** [comment]
Thanks for reporting the issue. We've fixed the README.md.
